/** Map GitLite / file extension language ids to Monaco editor language ids */
const LANGUAGE_MAP: Record<string, string> = {
  rs: "rust",
  rust: "rust",
  ts: "typescript",
  tsx: "typescript",
  typescript: "typescript",
  js: "javascript",
  jsx: "javascript",
  javascript: "javascript",
  mjs: "javascript",
  cjs: "javascript",
  json: "json",
  jsonc: "json",
  sh: "shell",
  bash: "shell",
  zsh: "shell",
  py: "python",
  python: "python",
  java: "java",
  cpp: "cpp",
  cxx: "cpp",
  cc: "cpp",
  c: "cpp",
  h: "cpp",
  cs: "csharp",
  go: "go",
  php: "php",
  rb: "ruby",
  swift: "swift",
  kt: "kotlin",
  scala: "scala",
  sql: "sql",
  yaml: "yaml",
  yml: "yaml",
  xml: "xml",
  html: "html",
  htm: "html",
  css: "css",
  scss: "scss",
  sass: "scss",
  less: "less",
  md: "markdown",
  markdown: "markdown",
  diff: "plaintext",
  txt: "plaintext",
  text: "plaintext",
};

export function toMonacoLanguage(language: string): string {
  const key = language.trim().toLowerCase();
  return LANGUAGE_MAP[key] || key || "plaintext";
}
